# Header

menu:
  ä¸»é¡µ: /
  æ—¥è®°: /categories/æ—¥è®°
  æ•°æ®å¯è§†åŒ–: /categories/æ•°æ®å¯è§†åŒ–  
  # åˆ†ç±»: /categories/
  å½’æ¡£: /archives/

# SubNav
subnav:
  github: "https://github.com/cyz980908/"
  juejin: "https://juejin.im/user/5b0c17fa6fb9a00a33588df7"
  ins: "https://www.instagram.com/98_cyz/"
  # weibo: "#"
  # rss: "#"
  # zhihu: "#"
  #qq: "462065470"
  #weixin: "cyz__98"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  bilibili: "https://space.bilibili.com/22624981?from=search&seid=461345324992575383"
  #acfun: "#"
  mail: "mailto:462065470@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "@yizhiChen5"
  #linkedin: "#"

rss: /atom.xml

# æ˜¯å¦éœ€è¦ä¿®æ”¹ root è·¯å¾„
# å¦‚æœæ‚¨çš„ç½‘ç«™å­˜æ”¾åœ¨å­ç›®å½•ä¸­ï¼Œä¾‹å¦‚ http://yoursite.com/blogï¼Œ
# è¯·å°†æ‚¨çš„ url è®¾ä¸º http://yoursite.com/blog å¹¶æŠŠ root è®¾ä¸º /blog/ã€‚
root: /

# Content

# æ–‡ç« å¤ªé•¿ï¼Œæˆªæ–­æŒ‰é’®æ–‡å­—
excerpt_link: 
# æ–‡ç« å¡ç‰‡å³ä¸‹è§’å¸¸é©»é“¾æ¥ï¼Œä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
show_all_link: 'å±•å¼€å…¨æ–‡'
# æ•°å­¦å…¬å¼
mathjax: true
# æ˜¯å¦åœ¨æ–°çª—å£æ‰“å¼€é“¾æ¥
open_in_new: true

# æ‰“èµ
# æ‰“èµtypeè®¾å®šï¼š0-å…³é—­æ‰“èµï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰reward:trueå±æ€§ï¼Œæ‰æœ‰æ‰“èµï¼› 2-æ‰€æœ‰æ–‡ç« å‡æœ‰æ‰“èµ
reward_type: 2
# æ‰“èµwording
reward_wording: 'è°¢ä¸»éš†æ©ï¼'
# æ”¯ä»˜å®äºŒç»´ç å›¾ç‰‡åœ°å€ï¼Œè·Ÿä½ è®¾ç½®å¤´åƒçš„æ–¹å¼ä¸€æ ·ã€‚æ¯”å¦‚ï¼š/assets/img/alipay.jpg
alipay: "/images/alipay.jpg"
# å¾®ä¿¡äºŒç»´ç å›¾ç‰‡åœ°å€
weixin: "/images/wechatpay.jpg"

# ç›®å½•
# ç›®å½•è®¾å®šï¼š0-ä¸æ˜¾ç¤ºç›®å½•ï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰toc:trueå±æ€§ï¼Œæ‰æœ‰ç›®å½•ï¼› 2-æ‰€æœ‰æ–‡ç« å‡æ˜¾ç¤ºç›®å½•
toc: 2
# æ ¹æ®è‡ªå·±çš„ä¹ æƒ¯æ¥è®¾ç½®ï¼Œå¦‚æœä½ çš„ç›®å½•æ ‡é¢˜ä¹ æƒ¯æœ‰æ ‡å·ï¼Œç½®ä¸ºtrueå³å¯éšè—hexoé‡å¤çš„åºå·ï¼›å¦åˆ™ç½®ä¸ºfalse
toc_hide_index: true
# ç›®å½•ä¸ºç©ºæ—¶çš„æç¤º
toc_empty_wording: 'ç›®å½•ï¼Œä¸å­˜åœ¨çš„â€¦'

# æ˜¯å¦æœ‰å¿«é€Ÿå›åˆ°é¡¶éƒ¨çš„æŒ‰é’®
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /img/favicon.png

#ä½ çš„å¤´åƒurl
avatar: "/images/avatar.jpg"

#æ˜¯å¦å¼€å¯åˆ†äº«
share_jia: true

#è¯„è®ºï¼š1ã€å¤šè¯´ï¼›2ã€ç½‘æ˜“äº‘è·Ÿå¸–ï¼›3ã€ç•…è¨€ï¼›4ã€Disqusï¼›5ã€Gitment
#ä¸éœ€è¦ä½¿ç”¨æŸé¡¹ï¼Œç›´æ¥è®¾ç½®å€¼ä¸ºfalseï¼Œæˆ–æ³¨é‡Šæ‰
#å…·ä½“è¯·å‚è€ƒwikiï¼šhttps://github.com/litten/hexo-theme-yilia/wiki/

#1ã€å¤šè¯´
duoshuo: false

#2ã€ç½‘æ˜“äº‘è·Ÿå¸–
wangyiyun: false

#3ã€ç•…è¨€
changyan_appid: false
changyan_conf: false

#4ã€Disqus åœ¨hexoæ ¹ç›®å½•çš„configé‡Œä¹Ÿæœ‰disqus_shortnameå­—æ®µï¼Œä¼˜å…ˆä½¿ç”¨yiliaçš„
disqus: false

#5ã€Gitment
gitment_owner: false      #ä½ çš„ GitHub ID
gitment_repo: ''          #å­˜å‚¨è¯„è®ºçš„ repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# æ ·å¼å®šåˆ¶ - ä¸€èˆ¬ä¸éœ€è¦ä¿®æ”¹ï¼Œé™¤éæœ‰å¾ˆå¼ºçš„å®šåˆ¶æ¬²æœ›â€¦
style:
  # å¤´åƒä¸Šé¢çš„èƒŒæ™¯é¢œè‰²
  header: '#4d4d4d'
  # å³æ»‘æ¿å—èƒŒæ™¯
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# sliderçš„è®¾ç½®
slider:
  # æ˜¯å¦é»˜è®¤å±•å¼€tagsæ¿å—
  showTags: false

# æ™ºèƒ½èœå•
# å¦‚ä¸éœ€è¦ï¼Œå°†è¯¥å¯¹åº”é¡¹ç½®ä¸ºfalse
# æ¯”å¦‚
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: 'æ‰€æœ‰æ–‡ç« '
  friends: 'å°ä¼™ä¼´ä»¬'
  aboutme: 'çŒœçŒœæˆ‘æ˜¯è°ï¼Ÿ'

friends:
  æ°´å“¥: https://blog.lucien.ink
  å‹æƒ…é“¾æ¥2: http://localhost:4000/
  å‹æƒ…é“¾æ¥3: http://localhost:4000/
  å‹æƒ…é“¾æ¥4: http://localhost:4000/
  å‹æƒ…é“¾æ¥5: http://localhost:4000/
  å‹æƒ…é“¾æ¥6: http://localhost:4000/

aboutme: ä½ å¥½å‘€<br>è°¢è°¢ä½ å‘ç°äº†æˆ‘ğŸ’—<br>é™ˆä»¥ä¹‹ æœ€ä¼šè·³èˆçš„ç¨‹åºå‘˜

#6ã€Valine https://valine.js.org
valine: 
 appid:  DmgkGtEU9Ubz29JTw0l021SV-gzGzoHsz #Leancloudåº”ç”¨çš„appId
 appkey:  okgoPt2o3ecvTkfpgXMot2gg  #Leancloudåº”ç”¨çš„appKey
 verify: true #éªŒè¯ç 
 notify: true #è¯„è®ºå›å¤æé†’
 avatar: mm #è¯„è®ºåˆ—è¡¨å¤´åƒæ ·å¼ï¼š''/mm/identicon/monsterid/wavatar/retro/hide
 placeholder: ğŸ§™â€â™€ï¸ #è¯„è®ºæ¡†å ä½ç¬¦

 # Post wordcount display settings
# Dependencies: https://github.com/willin/hexo-wordcount
word_count: true